[versions]
adapterRxjava3                  = "3.0.0"
agp                             = "8.13.2"
browser                         = "1.9.0"
coreSplashscreen                = "1.2.0"
credentials                     = "1.5.0"
credentialsPlayServicesAuth     = "1.5.0"
facebookLogin                   = "18.1.3"
firebaseBom                     = "34.8.0"
firebaseUiAuth                  = "9.1.1"
glide                           = "5.0.5"
googleid                        = "1.2.0"
junit                           = "4.13.2"
junitVersion                    = "1.3.0"
espressoCore                    = "3.7.0"
appcompat                       = "1.7.1"
material                        = "1.14.0-alpha09"
activity                        = "1.12.2"
constraintlayout                = "2.2.1"
cardview                        = "1.0.0"
navigationFragment              = "2.9.7"
navigationUi                    = "2.9.7"
annotation                      = "1.9.1"
lifecycleLivedataKtx            = "2.10.0"
lifecycleViewmodelKtx           = "2.10.0"
loggingInterceptor              = "5.3.2"
retrofit                        = "3.0.0"
googleGmsServicesVersion        = "4.4.4"
rxandroid                       = "3.0.2"
rxjava                          = "3.1.12"
safeArgs                        = "2.9.7"


[libraries]
adapter-rxjava3                 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "adapterRxjava3" }
browser                         = { module = "androidx.browser:browser", version.ref = "browser" }
core-splashscreen               = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
credentials-play-services-auth  = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
credentials                     = { module = "androidx.credentials:credentials", version.ref = "credentials" }
facebook-login                  = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
firebase-auth                   = { module = "com.google.firebase:firebase-auth" }
firebase-analytics              = { module ="com.google.firebase:firebase-analytics" }
firebase-bom                    = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-ui-auth                = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
glide                           = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
googleid                        = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
junit                           = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit                       = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core                   = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat                       = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material                        = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity                        = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout                = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
cardview                        = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
navigation-ui                   = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
navigation-fragment             = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
annotation                      = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx          = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx         = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
logging-interceptor             = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
converter-gson                  = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit                        = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid                       = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava                          = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

[plugins]
android-application             = { id = "com.android.application", version.ref = "agp" }
google-gms-services             = {id = "com.google.gms.google-services", version.ref = "googleGmsServicesVersion"}
safe-args                       = {id = "androidx.navigation.safeargs", version.ref = "safeArgs"}